### ISSUE TITLE
React/RCTViewManager.h file not found

### ISSUE THREAD

**Issue by MarvinSantos** [Kerumen/react-native-awesome-card-io#24]
hey, very nice lib, thanks. 
i am having this error on ios with react-native v0.39.2
can you check this?

**Comment by Kerumen** [comment]
iOS imports were changed (https://github.com/Kerumen/react-native-awesome-card-io/commit/df813181fc0c84c8b4cf8774be6ad908d55eeeee) due to a [breaking change in React Native v0.40](https://github.com/facebook/react-native/wiki/Breaking-Changes#040).
This change was published in v0.6.0.
Hence, this library only support the latest React Native version.

You have to stick with v0.5.0 for React Native v0.39.2.

**Comment by matrpedreira** [comment]
I'm having this error using React Native v0.43.3.

**Comment by matrpedreira** [comment]
My bad, I was having the issue because I was importing React using pods and this was causing some conflicts.

**Comment by piyush565** [comment]
/Users/../node_modules/react-native-material-kit/iOS/RCTMaterialKit/TickViewManager.m:9:9: 'React/RCTViewManager.h' file not found

can anybody help me with this.? build gets failed in this

**Comment by Kerumen** [comment]
This is not even this library. Maybe file an issue [here](https://github.com/xinthink/react-native-material-kit)?

**Comment by piyush565** [comment]
got it thanks, posted there :)
